/* Plain-language cinematography vocabulary. No external services required. */
window.PBCinema = (() => {
 const O=(label,help,wording=label)=>({label,help,wording});
 const list=s=>s.split('|').map(label=>O(label,`Request ${label.toLowerCase()}. Choose this when it matches the intended scene; leave blank to let the generator decide.`));
 const F=(id,label,options,help='',advanced=false)=>({id,label,options:typeof options==='string'?list(options):options,help,advanced});
 const T=(id,label,placeholder='',advanced=false)=>({id,label,placeholder,kind:'text',advanced});
 const M=(id,label,options,help='',advanced=false)=>({...F(id,label,options,help,advanced),kind:'multi'});
 const identity="Use the uploaded portrait as the exact facial reference. Preserve 100% of the person's identity, including facial structure, hairstyle, skin tone, facial proportions, jawline, eyes, nose, lips, expression, age, and all distinctive features. Do not alter, beautify, or replace the face.";
 const restrictions=[
 ['Identity & continuity',[
 O('Portrait identity preservation','Attach the portrait in your image/video generator. This builder only writes the instruction; exact identity is a request, not a guarantee. Preserving expression can conflict with a new emotion.',identity),
 O('No face morphing','Keep facial geometry stable across frames. Useful for close-ups.','Do not morph or change facial features across frames.'),
 O('Consistent age & skin tone','Avoid unintended age or complexion changes.','Preserve age and skin tone throughout.'),
 O('Consistent wardrobe','Keep clothing, accessories and colors unchanged.','Maintain consistent clothing, accessories and colors.'),
 O('Consistent hairstyle','Prevent hair length, color or style changing between frames.','Keep hairstyle, hair color and hair length consistent.'),
 O('No duplicate subjects','Avoid accidental clones in a scene.','Do not duplicate the subjects.'),
 O('No extra people','Preserve only the specified cast.','Do not introduce unspecified people.'),
 O('Stable props & environment','Avoid objects appearing, disappearing or changing shape.','Maintain prop and environment continuity; no spontaneous objects or disappearing props.'),
 O('Correct anatomy','Request plausible bodies and joints.','Use anatomically plausible bodies, joints, hands and fingers; no extra or missing limbs.'),
 O('No object morphing','Keep objects from melting or transforming.','Do not morph, melt or transform objects unless explicitly requested.')]],
 ['Content boundaries',[
 O('No gore','Exclude graphic injuries and dismemberment.','No gore, graphic injury or dismemberment.'),O('No blood','Exclude visible blood.','No visible blood.'),O('No violence','Keep actions nonviolent.','No violence or physical harm.'),O('No weapons','Exclude weapons from the scene.','No weapons.'),O('No nudity','Keep characters clothed.','No nudity; all characters remain clothed.'),O('No sexual content','Keep the scene nonsexual.','No sexual content or sexualized presentation.'),O('No hate symbols','Avoid hateful imagery or slogans.','No hate symbols or hateful slogans.'),O('No profanity','Exclude vulgar speech or visible wording.','No profanity in speech or visible text.'),O('No drugs or smoking','Exclude substance use and smoking.','No drugs, smoking or vaping.'),O('No alcohol','Exclude alcoholic drinks and alcohol use.','No alcohol or drinking alcohol.'),O('No animal harm','Keep animals unharmed.','No animal cruelty or harm.'),O('No frightening imagery','Avoid horror, jump scares and disturbing imagery.','No frightening imagery, horror or jump scares.')]],
 ['Image quality & overlays',[
 O('No text overlays','Avoid captions and generated labels.','No text overlays, captions or labels.'),O('No subtitles','Useful when dialogue should be audio only.','No subtitles.'),O('No watermarks','Request a clean image; this cannot remove a provider-required watermark.','Do not add decorative watermarks.'),O('No logos','Avoid unrequested branding.','No logos or brand marks.'),O('No timers or timestamps','Exclude counters and recording indicators.','No timers, countdowns, timestamps or recording indicators.'),O('No flicker','Keep brightness stable over time.','Avoid flicker and abrupt exposure changes.'),O('No jitter','Keep unintended frame-to-frame displacement out.','No unintended jitter or frame instability.'),O('No compression artifacts','Request clean textures and edges.','Avoid blockiness, compression artifacts and banding.'),O('No unwanted blur','Preserve intended focus; deliberate depth of field is still allowed.','No unintended blur; preserve deliberately selected depth of field and motion blur.'),O('No overexposed highlights','Retain detail in bright areas.','Preserve highlight detail; avoid unintended clipped highlights.'),O('No crushed shadows','Retain visible dark-area detail.','Preserve shadow detail; avoid unintended crushed blacks.'),O('No beauty retouching','Keep natural pores and facial texture.','No beauty retouching, skin smoothing or artificial facial enhancement.')]],
 ['Motion, composition & audio',[
 O('No cuts','Keep one continuous take.','Use one continuous shot with no cuts.'),O('No camera movement','Lock camera position and rotation. Conflicts with selected camera movements.','Use a locked-off camera; no camera movement or zoom.'),O('No abrupt movement','Request gentle transitions.','No abrupt camera or subject movement.'),O('No speed changes','Keep playback consistent.','No speed ramps or unintended playback-speed changes.'),O('No frame cropping','Keep the requested subject visible.','Do not unintentionally crop the main subject out of frame.'),O('No lens distortion','Avoid exaggerated geometry; may conflict with fisheye.','Avoid visible lens distortion.'),O('No lens flare','Keep stray light streaks out.','No lens flare.'),O('No dialogue','Use visuals and other audio only.','No spoken dialogue.'),O('No music','Useful for sound effects or dialogue-only scenes.','No background music.'),O('No audio','Request a silent result.','Silent output; no audio.'),O('No lip-sync mismatch','Keep mouth motion aligned with speech.','Match lip movements to the spoken dialogue.'),O('No audio clipping','Avoid distorted loud sound.','Avoid audio clipping, distortion and sudden volume jumps.')]]
 ];
 const sections=[
 {id:'project',title:'Project',desc:'Start with the format and the story you want to tell.',fields:[T('projectName','Project name','Example: A quiet morning in Manila'),F('platform','Target platform','Generic|Kling|Runway|Veo|Sora|Midjourney|Other','A label for your target tool. Availability of audio, duration and camera controls varies by model.'),F('outputType','Output','Video|Still image'),F('aspectRatio','Aspect ratio','16:9|9:16|1:1|4:3|3:2|2.39:1','16:9 is widescreen; 9:16 is vertical; 1:1 is square.'),F('duration','Video duration','5 seconds|8 seconds|10 seconds|15 seconds|30 seconds'),T('theme','Theme / concept','Example: cinematic travel portrait'),T('type','Genre / type','Example: documentary'),T('scene','Scene idea','One clear moment or situation')]},
 {id:'subject',title:'Subject & action',desc:'Who is in the scene, and what happens?',fields:[T('character','Subject / characters','Appearance, clothing, identity and distinguishing details'),T('action','Action','Describe a clear action, in order'),F('actionPace','Action pace','Still|Slow|Natural|Energetic|Fast'),F('orientation','Subject orientation',[O('Facing camera','The front of the subject faces the lens; direct eye contact is separate.'),O('Looking into lens','Subject makes eye contact with the viewer.'),O('Three-quarter view','Face or body turns partly toward camera; useful for dimensional portraits.'),O('Profile / side-on','See the subject from the side.'),O('Rear / from behind','Camera sees the subject’s back.'),O('Looking away','Subject looks away from the lens.')]),F('emotion','Emotion','Happy|Sad|Crying|Laughing|Calm|Worried|Frustrated|Contented|Hopeful|Angry|Afraid|Surprised|Confident|Thoughtful|Neutral'),F('performance','Performance','Subtle and natural|Expressive|Restrained|Theatrical|Documentary candid'),T('expressionNotes','Expression / performance notes','Example: a slight smile, relaxed shoulders')]},
 {id:'environment',title:'Environment',desc:'Give the scene a place, time and atmosphere.',fields:[T('location','Location','Example: a quiet coastal road'),T('surroundings','Surroundings','Background, props, colors and atmosphere'),F('timeOfDay','Time of day','Dawn|Sunrise|Morning|Midday|Afternoon|Golden hour|Sunset|Blue hour|Dusk|Night','Golden hour is warm low-angle sunlight near sunrise/sunset; blue hour is cool twilight.'),F('weather','Weather','Clear / sunny|Partly cloudy|Overcast|Rain|Drizzle|Stormy|Fog|Mist|Snow|Windy'),T('atmosphere','Atmosphere notes','Example: thin sea mist with a gentle breeze')]},
 {id:'camera',title:'Framing & movement',desc:'Framing is how much you see. Angle is where you look from. Movement is how the camera travels.',fields:[
 F('shot','Shot / framing',[O('Extreme wide / establishing','Subject is tiny or absent; introduce the setting.'),O('Very wide','Show a small subject within a broad environment.'),O('Wide / long shot','Show the whole subject and plenty of surroundings.'),O('Full shot','Frame a person from head to toe.'),O('Medium full / cowboy','Frame from about mid-thigh upward.'),O('Medium shot','Frame about waist upward; useful for conversation.'),O('Medium close-up','Frame chest upward; emphasize expression.'),O('Close-up','Face or object fills most of the frame.'),O('Extreme close-up','Isolate a very small feature such as an eye.'),O('Insert / detail shot','Show an important object or action detail.')]),
 F('angle','Camera angle / viewpoint',[O('Eye level','Lens sits near eye height for a neutral view.'),O('Low angle','Look upward at the subject for a powerful impression.'),O('High angle','Look downward at the subject.'),O("Worm’s-eye view",'Extreme ground-level angle looking upward.'),O("Bird’s-eye view",'Look down from high above; useful for geography.'),O('Top-down / overhead','Point the camera straight downward.'),O('Dutch angle','Tilt the horizon diagonally to create unease.'),O('POV / first person','See what the character sees.'),O('Over-the-shoulder','Look past one person’s shoulder toward another subject.')]),
 F('composition','Composition','Centered|Rule of thirds|Symmetrical|Negative space|Leading lines|Two shot|Three shot|Group shot|Reaction shot','Composition arranges elements inside the frame. A two shot includes two subjects; a reaction shot emphasizes a response.'),
 M('movements','Camera movements',[
 O('Pan left','Rotate the camera left from a fixed position; reveal the scene.','Pan left'),O('Pan right','Rotate right from a fixed position.','Pan right'),O('Tilt up','Rotate the lens upward without raising the camera.'),O('Tilt down','Rotate the lens downward without lowering the camera.'),O('Zoom in','Increase focal length; tighten framing without moving the camera.'),O('Zoom out','Decrease focal length; widen framing without moving the camera.'),O('Dolly in','Physically move toward the subject; foreground and background relationships change.'),O('Dolly out','Physically move away from the subject.'),O('Truck left','Move the whole camera sideways to the left.'),O('Truck right','Move the whole camera sideways to the right.'),O('Track / follow','Travel with a moving subject to keep it framed.'),O('Pedestal up','Raise the whole camera vertically, without tilting.'),O('Pedestal down','Lower the whole camera vertically, without tilting.'),O('Crane / jib rise','Sweep upward on an elevated camera arm; useful for revealing a setting.'),O('Crane / jib descend','Sweep down toward the scene using an elevated arm.'),O('Roll','Rotate around the viewing axis; the horizon rotates.'),O('Orbit clockwise','Travel around the subject clockwise.'),O('Orbit counterclockwise','Travel around the subject counterclockwise.'),O('Dolly zoom','Dolly while zooming in the opposite direction to hold subject size while changing background perspective.'),O('Drone flyover','Fly above and across the setting.'),O('Drone reveal','Rise or move past an obstruction to reveal a landscape.')], 'Select one or more. They are written in selection order; choose sequential or simultaneous execution below.'),
 F('movementOrder','Movement combination','Sequential, in selection order|Simultaneous, coordinated','Sequential movements happen one after another. Simultaneous moves combine, such as a dolly-in with a tilt-up.'),
 F('cameraPace','Movement speed','Very slow|Slow|Natural|Fast|Whip / rapid'),F('movementQuality','Movement quality','Smooth and steady|Gentle ease-in / ease-out|Constant speed|Organic and imperfect|Abrupt and energetic'),
 F('cameraSupport','Camera support / handling',[O('Locked tripod','Camera remains stationary. Avoid combining with travel moves.'),O('Tripod head','Stable support for pan and tilt.'),O('Handheld','Human-held camera with natural small shakes; documentary feel.'),O('Gimbal','Motorized stabilization for smooth walking or travelling shots.'),O('Steadicam','Body-mounted mechanical stabilization for smooth floating movement.'),O('Dolly / track rig','Wheeled camera support for smooth guided travel.'),O('Crane / jib','Camera mounted on an arm for sweeping elevation changes.'),O('Drone','Airborne camera platform; choose a viewpoint and flight movement separately.')]),T('movementNotes','Movement direction / sequence notes','Example: track behind the subject, then gently orbit to reveal their face') ]},
 {id:'optics',title:'Lens & focus',desc:'Start with the look. Advanced mode lets you describe the optical settings behind it.',fields:[
 F('depth','Depth of field',[O('Shallow depth of field','Only a narrow distance range looks sharp; background is soft. Useful for separating a portrait.'),O('Moderate depth of field','Keep the subject and some context recognizable.'),O('Deep focus','Keep near and distant scene elements acceptably sharp; useful for landscapes.')]),
 F('focus','Focus behavior',[O('Focus on subject','Keep the main subject sharp.'),O('Eye focus','Prioritize sharp eyes; useful for portraits.'),O('Rack focus','Shift focus between subjects or distances during the shot.'),O('Manual fixed focus','Focus stays at one distance; subjects can move into or out of focus.'),O('Soft focus','Deliberately lower fine-detail contrast for a dreamy effect.'),O('Defocus','Make the scene intentionally out of focus.')]),T('focusTarget','Focus target / transition','Example: focus on the hand, then rack focus to the face'),
 F('focalLength','Focal length','14mm ultra-wide|24mm wide|35mm environmental|50mm normal|85mm portrait|135mm telephoto|200mm long telephoto','Full-frame-equivalent descriptions. Shorter focal lengths show a wider view. Perspective depends on camera position; focal length changes framing.',true),
 F('lens','Lens character','Spherical / natural|Anamorphic|Macro|Fisheye|Tilt-shift|Vintage lens','Anamorphic suggests oval bokeh and horizontal flares; macro reveals tiny details; fisheye intentionally curves straight lines; tilt-shift changes the focus plane or framing.',true),
 F('aperture','Aperture','f/1.4|f/2|f/2.8|f/4|f/5.6|f/8|f/11|f/16','Lower f-numbers mean a wider opening and usually shallower depth of field. Higher f-numbers generally increase depth of field. Distance and focal length also matter.',true),
 F('fps','Frame rate','24 fps|25 fps|30 fps|60 fps','24–30 fps are common normal-speed choices. 60 fps can support smoother motion or slow playback when conformed to a lower frame rate.',true),
 F('shutter','Shutter speed','1/48 s|1/50 s|1/60 s|1/120 s|1/250 s|1/500 s|1/1000 s','Longer exposures create more motion blur. For natural video blur, a common starting point is about 1/(2 × frame rate), such as 1/48 at 24 fps.',true),
 F('iso','ISO','100|200|400|800|1600|3200|6400','ISO changes image brightness for a given exposure. Higher ISO can reveal more noise and reduce highlight latitude. These are visual cues for AI, not a physical camera exposure calculation.',true),
 F('exposure','Exposure look','Balanced / preserve highlights|Bright / airy|Dark / moody','A stylistic brightness target. Choose balanced as a general starting point.',true),
 F('motionBlur','Motion blur','Natural cinematic blur|Minimal / crisp motion|Pronounced motion trails','Motion blur comes from movement during exposure. It is different from an out-of-focus background.',true),
 F('whiteBalance','White balance','Neutral|Warm|Cool|Daylight ~5600K|Tungsten ~3200K','White balance compensates for illumination color. Describe warm/cool appearance directly when you want a creative color cast.',true),
 F('filter','Optical filter','None|ND / neutral density|Circular polarizer|Subtle diffusion','ND reduces light without intentionally changing color; a polarizer can reduce certain reflections; diffusion softens highlights.',true),
 F('bokeh','Bokeh / flare','Subtle circular bokeh|Oval bokeh|Soft highlight bloom|Controlled horizontal flare|No flare','Bokeh is the appearance of out-of-focus highlights. Flare is stray light inside a lens.',true)]},
 {id:'lighting',title:'Lighting & style',desc:'Choose the direction of light, its softness, and the visual treatment.',fields:[
 F('lightDirection','Light direction',[O('Front lighting','Light faces the subject from near the camera; details read clearly.'),O('Side lighting','Light from one side emphasizes shape and texture.'),O('Back lighting','Light behind the subject separates edges from background.'),O('Rim lighting','A narrow bright edge outlines the subject.'),O('Top lighting','Light from above creates downward shadows.'),O('Underlighting','Light from below creates an unusual or eerie impression.')]),
 F('lightQuality','Light quality',[O('Soft light','Gradual shadow edges; flattering, gentle appearance.'),O('Hard light','Crisp shadow edges; bold shape and texture.'),O('Diffused overcast','Broad sky illumination with gentle shadows.')]),
 F('lightStyle','Lighting style',[O('Natural light','Use plausible sun, sky or available light.'),O('High-key','Bright scene with low contrast and limited deep shadows.'),O('Low-key','Dark scene with selected illuminated areas and strong contrast.'),O('Silhouette','Expose for the bright background so the subject becomes a dark outline.'),O('Three-point lighting','Key, fill and back light separate and shape the subject.'),O('Practical lighting','Visible lamps, signs or candles motivate the illumination.'),O('Volumetric lighting','Visible light beams through haze or particles.'),O('Neon lighting','Colored illuminated signs create saturated accents.')]),
 F('style','Art / visual style','Photorealistic|Cinematic realism|Documentary|Editorial photography|Film noir|Analog film|Watercolor|Oil painting|Gouache|Ink illustration|Pencil sketch|Anime|Manga|Comic book|Cel animation|3D animation|Claymation|Stop motion|Low-poly 3D|Pixel art|Paper cutout|Collage|Surrealism|Art nouveau|Art deco|Minimalist|Cyberpunk|Steampunk|Retro-futurism','Choose one primary style to keep direction clear. Add specific texture, palette or medium details below.'),
 T('styleNotes','Palette / texture / style notes','Example: muted teal and amber, subtle film grain'),T('lighting','Additional lighting notes','Example: soft window light from camera left')]},
 {id:'audio',title:'Dialogue & audio',desc:'Optional sound direction for models that support audio.',fields:[T('dialogueEnglish','Dialogue / meaning','Exact spoken line or English meaning'),T('dialogueLanguage','Spoken language','Example: English or Filipino'),T('dialogueRomanized','Exact romanized dialogue','Optional exact pronunciation in Latin letters'),T('dialogueNotes','Voice / delivery','Example: calm, warm delivery with a brief pause'),F('musicEnabled','Background music','Yes|No'),T('musicGenre','Music direction','Example: gentle acoustic guitar'),T('soundEffects','Sound effects / ambience','Example: waves, footsteps and a light breeze'),F('audioPriority','Mix priority','Dialogue first|Music first|Ambience first|Balanced'),F('audioDucking','Audio ducking','Lower music during dialogue|Always keep music low|No ducking','Ducking automatically reduces other sounds while speech is present.')]},
 {id:'restrictions',title:'Restrictions',desc:'Select only what matters. Normal is a preference, Important is emphasized, and Critical is a must-follow request—not a guarantee.',fields:[T('negativePrompt','Custom restrictions','Add any limits not listed above'),T('notes','Additional notes','Other creative instructions')]},
 {id:'review',title:'Review & generate',desc:'Check your choices, resolve conflicting directions, and copy your finished prompt.',fields:[]}
 ];
 const explanations={
 'Spherical / natural':'Conventional lens rendering with relatively natural shapes; use for a clean photographic look.',
 'Anamorphic':'A widescreen lens aesthetic with oval bokeh and possible horizontal flares; useful for stylized cinema.',
 'Macro':'Close focusing reveals small objects and textures at large scale; useful for insects, jewelry and fine details.',
 'Fisheye':'An extremely wide view with curved straight lines; useful for deliberately exaggerated scenes.',
 'Tilt-shift':'Changes the focus plane or framing; a selective focus band can suggest a miniature scene.',
 'Vintage lens':'Suggests older optical character such as softer edges, lower contrast or imperfect flare.',
 'Photorealistic':'Aim for the textures, lighting and proportions of a real photograph.',
 'Cinematic realism':'Realistic imagery with deliberate film-like framing, light and color.',
 'Documentary':'Observational, believable imagery with a candid, unstaged feel.',
 'Editorial photography':'A polished visual story with controlled styling and composition.',
 'Film noir':'Strong light/shadow contrast, often monochrome, for a tense classic crime-film look.',
 'Analog film':'Suggest photochemical grain, organic texture and a film-like tonal response.',
 'Watercolor':'Translucent washes, soft edges and paper texture for a light painted feel.',
 'Oil painting':'Layered pigment and visible brushwork, often with rich color and texture.',
 'Gouache':'Opaque matte painted colors and clear shapes, useful for bold illustration.',
 'Ink illustration':'Expressive lines and hatching with strong contrast.',
 'Pencil sketch':'Graphite-like lines and shading with visible drawing texture.',
 'Anime':'Stylized animation with expressive characters and designed shapes.',
 'Manga':'Comic-page aesthetics using ink linework, screen tones and expressive framing.',
 'Comic book':'Outlined characters, graphic shapes and bold illustrative shading.',
 'Cel animation':'Flat color regions with clean outlines and stepped shading.',
 '3D animation':'Volumetric modeled forms with rendered materials and lighting.',
 'Claymation':'Sculpted clay textures and handcrafted stop-motion character.',
 'Stop motion':'A tactile frame-by-frame animation look with discrete movement.',
 'Low-poly 3D':'Simplified faceted geometry with visibly angular forms.',
 'Pixel art':'Deliberate pixel-grid shapes and a limited palette; use for retro game imagery.',
 'Paper cutout':'Layered flat paper shapes with visible edges and shallow shadows.',
 'Collage':'A composition assembled from distinct visual fragments and textures.',
 'Surrealism':'Dreamlike imagery with unexpected scale, relationships or impossible combinations.',
 'Art nouveau':'Flowing organic lines and decorative floral motifs.',
 'Art deco':'Geometric ornament, symmetry and elegant streamlined forms.',
 'Minimalist':'Few elements, restrained colors and generous empty space.',
 'Cyberpunk':'High-tech urban imagery with dense detail and often neon-lit contrast.',
 'Steampunk':'Retro industrial machinery with Victorian-inspired materials and design.',
 'Retro-futurism':'Past eras’ imagined futures, combining vintage design and speculative technology.'
 };
 sections.flatMap(s=>s.fields).forEach(f=>f.options?.forEach(o=>{if(explanations[o.label])o.help=explanations[o.label];}));
 const audio=sections.find(s=>s.id==='audio');
 audio.fields.push(T('musicStyle','Music mood','Example: restrained and hopeful',true),T('tempo','Music tempo','Example: slow, 70 BPM',true),F('voiceVolume','Relative voice level','0%|25%|50%|75%|85%|100%','Descriptive mix balance, not a calibrated loudness measurement.',true),F('musicVolume','Relative music level','0%|10%|25%|35%|50%|75%|100%','Keep music below speech when dialogue is important.',true),F('sfxVolume','Relative effects level','0%|25%|50%|65%|75%|100%','How prominent sound effects should feel compared with other audio.',true));
 return {sections,restrictions,identity};
})();
